# Generated by Django 5.0.7 on 2024-07-24 06:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops_app', '0005_shop_avg_rating_shop_total_ratings_shopreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reviews', to='shops_app.shop'),
        ),
    ]
